ModelBehaviorDefs/Asobo/Airliner/Boeing.xml
SimObjects/Airplanes/Asobo_B747_8i/model/747_8I_INTERIOR.xml

Hi,
I just made the air conditioning knobs functionally, so the are no longer INOP.
Screenshots:

Made air cond Knobs functional

---

html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/EICAS/Pages/B747_8_LowerEICAS_FCTL.css
html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/EICAS/Pages/B747_8_LowerEICAS_FCTL.js
layout.json
manifest.json

Hi,
Fix the trim color:
- Green when on the ground.
- White when in flight.

Fix FCTL trim color

---

html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/PFD/B747_8_PFD.html
html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/PFD/Boeing_FMA.html
html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/PFD/Boeing_FMA.js
layout.json
manifest.json

Fix FMA HOLD

---

html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/PFD/Boeing_FMA.js
layout.json
manifest.json

Fix #14 
Remove pre selected mode.

FMA pre selected mode fixed

---

html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/EICAS/B747_8_EICAS.html
html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/EICAS/B747_8_EICAS.js
html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/EICAS/Pages/B747_8_LowerEICAS_ELEC.css
html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/EICAS/Pages/B747_8_LowerEICAS_ELEC.html
html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/EICAS/Pages/B747_8_LowerEICAS_ELEC.js
layout.json
manifest.json

EICAS Electrical page added.
Features:
-Engine GEN 1-4 status
-Main Bus 1-4 power Status
-BUS Tie 1-4 status
-EXT and APU 1&2 power status
-Split system breaker modelled

EICAS Electrical Page

---

html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/MFD/B747_8_MFD.html
html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/MFD/B747_8_MFD.js
layout.json
manifest.json

Fixes #40 
**Summary of changes** 
Waypoint data such as waypoint name, track, distance would be displayed on the ND only after IRS alignment is complete.

Waypoint on ND after IRS alignment

---

html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/EICAS/B747_8_EICAS.js
html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/PFD/AttitudeIndicator.js
html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/PFD/Boeing_FMA.js
layout.json
manifest.json

Fix #43 ==> already tested by 747-4EVER.
Fix #35 ==> blank lower eicas when selecting same page again.

Fix FMA modes on ground No.2 & Lower EICAS selection behavior

---

html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/PFD/AirspeedIndicator.js
html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/PFD/AttitudeIndicator.js
html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/PFD/Boeing_FMA.css

Porting PFD files from patch 1.9.3
Files:
- AirspeedIndicator.js
- AttitudeIndicator.js 
- Boeing_FMA.css

Porting PFD changes from patch 1.9.3

---

SimObjects/Airplanes/Asobo_B747_8i/panel/panel.xml
html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/MFD/B747_8_MFD.html
html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/MFD/B747_8_MFD.js

**Improves waypoint info at top of ND**
- Active waypoint now correctly displays in magenta
- ETA to waypoint now given in UTC instead of local time and reformatted (hidden until airborne)
- Distance to waypoint now given in correct format
- Deleted track display to waypoint (not on real aircraft)
- New UTC Clock feature on ND
- Deleted VOR arrows from bottom of ND (not on real aircraft)
- Misc formatting improvements
**Other:**
- Fixes EICAS TANK/ENG message not triggering correctly
- Changed altitude arc to correct (brighter) shade of green

ND Improvements

---

html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/EICAS/Pages/B747_8_LowerEICAS_DRS.html

Fixes #89 
Before: https://gyazo.com/c336d960823a72d1c4277b0ef91e7e49
After: https://gyazo.com/de8ba8d8c0a8bcfafd797cf5d141f57c

Removed F/D OVHD from DRS synoptic

---

SimObjects/Airplanes/Asobo_B747_8i/model/747_8I_INTERIOR.xml
html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/FMC/B747_8_FMC_MainDisplay.js
html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/MFD/B747_8_MFD.js
html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/PFD/B747_8_PFD.css
html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/PFD/B747_8_PFD.js
html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/PFD/Boeing_FMA.css

**Summary of changes**
* Changes in the interior model xml file (mostly related to lights)
* Miscellaneous FMC changes
* Minor changes in ND, PFD and FMA code (shouldn't change or affect anything)
Should have been done a long time ago, however I forgot about it.

Ported more Asobo changes

---

SimObjects/Airplanes/Asobo_B747_8i/panel/panel.xml

Fixes issue #98 
Changed message to PARK BRAKE SET and type to Advisory.

Fixes Parking Brake EICAS Message

---

html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/FMC/B747_8_FMC_VNAVPage.js

New improved model for VNAV CRZ maximum flight level.
Uses new equation derived from linear regression of 747-8I FCOM data for improved accuracy.
**FLmax = -0.02809mass + 56571.91142**

Improved Maximum Flight Level

---

html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/MFD/MapInstrument.js

Updates MapInstrument.js to Asobo version 1.14.5.0.

Map Hotfix

---

SimObjects/Airplanes/Asobo_B747_8i/engines.cfg

Continued from #131.
Only changes Fuel Burn, all changes to thrust and Fuel Flow Displays have been reverted.

Fixed Fuel Burn

---

html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/PFD/ILSIndicator.js

Fixed G/S pointer not displaying when selecting ILS approach in FMC.

Fixed G/S pointer bug

---

SimObjects/Airplanes/Asobo_B747_8i/panel/panel.xml
html_ui/Pages/VCockpit/Instruments/NavSystems/Shared/Salty_NavSystem.js
layout.json
manifest.json

Re-enabled Asobo Sounds.
Also reorganized Panel.xml by EICAS priority order.

Asobo Sound Fix

---

SimObjects/Airplanes/Asobo_B747_8i/model/747_8I.xml
layout.json
manifest.json

Added default model file for future diff purposes.

Add Default 747_8I.xml

---

html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/FMC/FMCMainDisplay.js

Fixed Bug caused by THR RED and ACC ALT having zero value when no flightplan present.

Fix THR RED alt bug

---

html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/FMC/FMCMainDisplay.js
layout.json
manifest.json

Ported some missing asobo changes from 1.14 which fixes the visual bug on the NAV/RAD page VOR entry fields.

Fix NAV RAD page bugs

---

html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/EICAS/Pages/B747_8_UpperEICAS.js
html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/FMC/FMCMainDisplay.js
html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/PFD/ILSIndicator.js
layout.json
manifest.json

ILS pointer fix
Changed max THR Ref value to 106%
Fixed in air spawn FlightPhase

More Bug Fixes

---

salty-747/SimObjects/Airplanes/Asobo_B747_8i/panel/panel.xml
salty-747/html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/PFD/AltimeterIndicator.js

Enabled minimums audio callout on approach.
Works for both Baro and Radio minimums settings.

Added Minimums Callout

---

salty-747/SimObjects/Airplanes/Asobo_B747_8i/panel/panel.xml
salty-747/html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/FMC/B747_8_FMC_MainDisplay.js
salty-747/html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/PFD/AltimeterIndicator.js

Added Altitude Alerting System.
Aural "C-Chord" warning combined with highlights to MCP altitude and current altitude on PFD.
Triggers when approaching 900 feet from MCP altitude, resets when within 200 feet.

Added MCP Altitude Alert

---

salty-747/html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/FMC/B747_8_FMC_MainDisplay.js

Small change to fix alt alert not triggering if climbing or descending at very high vertical speeds.

Alt Alert Bug Fix

---

salty-747/html_ui/Pages/Salty/SaltyBase.js
salty-747/html_ui/Pages/Salty/SaltyIRS.js
salty-747/html_ui/Pages/Salty/SaltyJettison.js
salty-747/html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/FMC/B747_8_FMC_MainDisplay.js

Issue #204 : IRS aligns even whilst electrical power unavailable.
I'm not sure what the correct behaviour is if the power is interrupted during alignment, the way I've done it the alignment timer pauses if power is lost, and continues from the same place once power returns.

fix issue #204 and correct minor fuel balancing bug

---

salty-747/SimObjects/Airplanes/Asobo_B747_8i/panel/panel.xml

Added JET NOZ ON(L/R) EICAS advisory messages triggered when Jettison is active.

Added Jettison EICAS messages

---

salty-747/html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/MFD/B747_8_MFD.html
salty-747/html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/MFD/B747_8_MFD.js
salty-747/html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/MFD/MapInstrument.html
salty-747/html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/MFD/MapInstrument.js
salty-747/html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/MFD/Svg/SvgFlightPlanElement.js

Added track line to ND expanded display modes with range labels and markers.
Range label adjusts its spacing slightly depending on if Weather Radar is selected on and aligns always to up.
Also fixed Altitude Range Arc to be z-indexed below the flightplan and waypoints, and aligned it with the aircraft current track, as it should be in heading up mode.
In order to layer these elements properly below waypoints, existing code had to be moved from the MFD to SvgFlightPlanElement.

ND Track Line

---

salty-747/html_ui/Pages/Salty/SaltyConnection.js
salty-747/html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/FMC/B747_8_FMC_RoutePage.js

- Airways now work when using SimBrief integration
- Coordinates mostly work

Re-implemented SimBrief integration for the WT FPM

---

salty-747/html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/FMC/B747_8_FMC_MainDisplay.js
salty-747/html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/FMC/Boeing_FMC.js
salty-747/html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/FMC/FMCMainDisplay.js

Prevents step climbing in VNAV from triggering the FMC descent mode due to oversight in default FMCMainDisplay.

Fixed Step Climb triggering FMC descent mode

---

salty-747/html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/FMC/B747_8_FMC_MainDisplay.js

Fixed bug causing VNAV to try to climb to Cruise Alt while in Descent mode if next waypoint had a constraint.

VNAV Bug Fix

---

salty-747/html_ui/Pages/Salty/SaltyConnection.js
salty-747/html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/FMC/B747_8_FMC_RoutePage.js

- All coordinates should now work in the RTE page and SimBrief regardless of the navdata.

User Waypoints in RTE page and SimBrief

---

salty-747/html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/MFD/Svg/SvgFlightPlanElement.js

Changes density of dashes drawn on ND by temporary flight plan causing performance issues on long routes.
Also fixes direct to line not being white and dashed.

ND dashes changes

---

salty-747/html_ui/Pages/Salty/SaltyConnection.js

- the first and last coordinate of a list of coordinates in a simbrief route should no longer be ignored
- cases where only one coordinate is present, resulting in something like "DCT 47S44 DCT" are now handled correctly

Fixed numerous SimBrief coordinate related bugs

---

salty-747/SimObjects/Airplanes/Asobo_B747_8i/flight_model.cfg
salty-747/html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/FMC/B747_8_FMC_PerfInitPage.js

Adds missing FL prefix to CRZ ALT field.

FMC PERF page fixes

---

salty-747/html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/EICAS/Pages/B747_8_LowerEICAS_ECL.js

Menu bug fix

---

salty-747/html_ui/Pages/Salty/WT/Autopilot/LNavDirector.js

Further LNAV Tuning

---

salty-747/html_ui/Pages/Salty/WT/Autopilot/SaltyNavModeSelector.js
salty-747/html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/FMC/Boeing_FMC.js
salty-747/html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/FMC/FMCMainDisplay.js

Fixes AT not activating when switched on if there was a mode change while it was disabled.

Autothrottle Switching Fix

---

salty-747/SimObjects/Airplanes/Asobo_B747_8i/panel/panel.xml

Adds HEAT WINDOW L & R advisory EICAS message when system is off.

Window Heat EICAS message

---

salty-747/html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/MFD/B747_8_MFD.js

Fix minor bug causing duplicate UTC indications.

ND info fix

---

salty-747/html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/MFD/B747_8_MFD.html
salty-747/html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/MFD/Salty_BaseNDCompass.js

Fixes heading bug and dashed line displaying before IRS is aligned.
Also better aligns TIME TO ALIGN text.

Fix Heading Bug on IRS alignment

---

salty-747/html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/FMC/B747_8_FMC_ProgPage.js

Fixes bug causing missed approach track to contribute to destination DTG. Now distance will read accurately.

Progress Page Fix

---

salty-747/SimObjects/Airplanes/Asobo_B747_8i/flight_model.cfg
salty-747/html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/EICAS/Boeing_Common.js

Normalised the flap position and commanded position indicator so that each setting is linearly spaced as per real aircraft.
Fixed Flap 1 position never reaching active "green" state. Flap 1 now properly indicates state of leading edge devices.
Fixed flap extension pause when passing each detent.

Fixed Flap Gauge

---

.ace/project.json
.gitignore
package-lock.json
package.json
src/instruments/rollup.config.js
src/instruments/src/Common/index.tsx
src/instruments/src/PFD/config.json
src/instruments/src/PFD/index.scss
src/instruments/src/PFD/index.tsx
src/instruments/tsconfig.json
src/tsconfig.json

- sets up prerequisites needed for ace

feat: ace and react instrument setup

---

salty-747/html_ui/Pages/Salty/WT/Autopilot/SaltyNavModeSelector.js
salty-747/html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/FMC/B747_8_FMC_MainDisplay.js

Fixes broken AP behaviour when engaging AP above 400' feet on takeoff.

fix(AP): Fixed broken AP behaviour on takeoff

---

src/modules/src/fpm/flightplanning/ManagedFlightPlan.ts

Provides a variable lead-in distance at start of direct leg to allow for turning onto new course without large overshoot.

fix(LNAV): Improves direct To leg tracking

---

src/models/build.js
src/models/models.json
src/models/pilots/pilots.gltf

Also, the merge script itself has also been slightly modified.
Added:
- Checking for the presence in the merged model: bufferViews, accessors, meshes, buffers
- If the node does not have mesh, then do not add it to the node.
- All models to be merged must have "lods" definition. This indicates which lods the changes will be made to.

Added: pilots.gltf with PILOT_0 and PILOT_1 nodes for merging.

---

salty-747/html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/FMC/ATC/B747_8_FMC_ATC_Message.js
salty-747/html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/FMC/B747_8_FMC_SelectWptPage.js
salty-747/html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/FMC/COMM/B747_8_FMC_COMM_Message.js
salty-747/html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/FMC/COMM/B747_8_FMC_COMM_Telex.js

**Testing instructions**
1. Add a waypoint to your route that has a duplicate with the same name but a different location, that would cause the "SELECT DESIRED WPT" page to display.
2. Check to see if the list of waypoints is sorted by distance, by looking up the coordinates.

feat(cdu): sort waypoints by proximity on select desired WPT page

---

salty-747/html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/FMC/FMCMainDisplay.js

fixes a bug that caused simbrief import to not work

fix(fmc): fix broken simbrief import

---

salty-747/html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/FMC/COMM/B747_8_FMC_COMM_Log.js

* fixes a bug where opening an acars message would lead to the atc log page

fix(fmc): acars messages

---

salty-747/html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/FMC/COMM/B747_8_FMC_COMM_Message.js

Just a small fix to the ACARS messages when switching pages.

fix(fmc): acars messages when transitioning from page to page

---

salty-747/SimObjects/Airplanes/Asobo_B747_8i/model/747_8I.xml
salty-747/SimObjects/Airplanes/Asobo_B747_8i/model/747_8I_INTERIOR.xml

Reverts split wipers which became broken as of SU8 to Asobo default implementation of linked wipers until a fix can be found.
**Testing instructions:**
Test each wiper setting works as intended.

fix(Model) Reverts Wipers to working Asobo state

---

salty-747/SimObjects/Airplanes/Salty_B747_8i/panel/panel.xml

**Adds new EICAS Caution messages for:**
ENG X SHUTDOWN (When fuel control switch is off)
DOOR FWD CARGO (When door is open)
**Testing Instructions:
Check above messages are displayed only when conditions met.**

feat(EICAS) New Messages

---

salty-747/SimObjects/Airplanes/Salty_B747_8i/flight_model.cfg
salty-747/html_ui/Pages/Salty/SaltyPayloadConstructor.js

* Fixes a bug where pilots were not visible in exterior or interior view

fix: pilots not visible

---

salty-747/SimObjects/Airplanes/Salty_B747_8i/engines.cfg

Update fuel flow to account for performance changes introduced in SU11. Calculated on previous data and tested.

feat: updated fuel flow

---

src/instruments/src/EFB/components/TopBar.tsx

Converts single quotation marks to double from https://github.com/saltysimulations/salty-747/pull/503

chore: Convert to double quotation marks for PR 503

---

src/instruments/src/EFB/apps/Aircraft/FuelPayload.tsx
src/instruments/src/EFB/apps/Home/index.tsx

fixes a bug where "kg" would be displayed when weight is in pounds

fix: wrong unit name when using lbs

---

salty-747/SimObjects/Airplanes/Salty_B747_8i/panel/panel.cfg
salty-747/html_ui/Pages/VCockpit/Instruments/b74s/mfd/MFD.css
salty-747/html_ui/Pages/VCockpit/Instruments/b74s/mfd/WTB748_MFD.html

Fixes an issue where flight dynamics break when spoilers are deployed on landing

fix: spoiler code for msfs2024
