saltysimulations/salty-747

- html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/MFD/B747_8_MFD.html
- html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/MFD/B747_8_MFD.js
- layout.json
- manifest.json
Resolves #27 
**Summary of changes** 
Now, the ND will show GS --- if the IRS is not aligned. 
Below 100 kts with aligned IRS, GS value will be indicated. 
TAS value, wind arrow, wind separator "/", wind speed and direction will be shown as long as the GS > 100 kts. 
GS value alignment changed slightly to the right for double/single digit GS values.
> ND Wind and TAS Display fixed

- html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/FMC/B747_8_FMC_PerfInitPage.js
- layout.json
- manifest.json
Cost index can be entered now, and couple of visual changes:
- "FL" before CRZ ALT.
- GR WT displays one digit after the decimal point.
> Cost index FMC

- html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/FMC/B747_8_FMC_VNAVPage.js
- layout.json
- manifest.json
Added some features to VNAV CRZ page on the FMC
- Page now refreshes automatically instead of on input
- Shows in title if ECON or MCP speed mode is active 
- Displays current command speed (was previously blank)
- Shows maximum operating flight level based on current aircraft weight
- Miscellaneous visual accuracy improvements
TO DO:
-Add step climb estimates
-Destination ETA and fuel
-Optimum and Recommended FL
> Improved FMC VNAV CRZ page

- html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/MFD/B747_8_MFD.js
Minor change of Altitude Range Arc behaviour.
From recent observations of the behaviour of the arc on the aircraft, I found that the arc disappears at 200 feet from the MCP altitude instead of the 100 that I originally had implemented.
> Minor Update Altitude Range Arc

- SimObjects/Airplanes/Asobo_B747_8i/flight_model.cfg
- html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/FMC/B747_8_FMC_VNAVPage.js
Adjusted empty CG position to a much more reasonable 26% MAC.
> Fixed empty aircraft CG

- html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/FMC/B747_8_FMC_ProgPage.js
Features from the previous progress page 1 implementation have been ported using the asobo default page as a base.
Differences from Asobo default include:
- Added ATC callsign to page title
- All ETAs now adjusted from local time to UTC
- Fuel estimates display to nearest 100lbs
- Added SEL SPD field showing current command speed or Mach
- Changed Layout to match real aircraft
- Deleted incorrect fields not present on real aircraft 
Note: T/D function has been disabled due to inaccuracies & needing improvement to logic.
Note: Active Waypoint should display Magenta, however Fmc.SetLine function does not seem to accept this as a valid colour.
FCOM Reference:
>  Ported Progress Features to Asobo base page

- SimObjects/Airplanes/Asobo_B747_8i/panel/panel.xml
Since Asobo fixed the armed status of the Spoilers in the model, we are now able to add the missing SPEEDBRAKE ARMED memo message to the EICAS.
> Added SPEEDBRAKE ARMED Memo

- salty-747/html_ui/Pages/Salty/SaltyUtils.js
- salty-747/html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/EICAS/B747_8_EICAS.html
- salty-747/html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/EICAS/Pages/B747_8_EICASGauge.js
Added a helper function SaltyUtils.setAttributes(), which should greatly improve readability (2 examples provided in PR). Tested working. If you ok this PR I will use the helper function to replace the large 'setAttribute' blocks in the code whenever I see them.
> Set attributes util

- salty-747/html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/EICAS/Pages/B747_8_UpperEICAS.js
Added green REV indication to Upper EICAS display when reverses are active.
Due to how the reverses work on the default aircraft, there is no "in transit" stage as the reverses deploy, so I haven't added the amber in transit indication for now.
> Added REV indication

- salty-747/SimObjects/Airplanes/Asobo_B747_8i/TEXTURE/B747_COCKPIT_TEXTS_ALBD.TIF.DDS.json
New Cockpit decals for all panels using Futura font.
Also added some missing misc details (PPG logo on Windshield, filled in compass swing card).
OVERHEAD PANEL
FORWARD PANEL / MCP
CDUs
WINDSHIELD
> Cockpit Decals

- salty-747/html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/PFD/AttitudeIndicator.js
Added Pitch Limit Indicator to PFD.
Shows pitch angle corresponding with stick shaker activation. Does not vary quite as real aircraft does as the MSFS flight model uses a fixed stall AOA that doesn't change with flaps.
Displays when Flaps 1 or greater, or when clean at "slow speeds". FCOM is ambiguous here so I used UP minus 20kts as an estimate.
> Pitch Limit Indicator

- salty-747/html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/FMC/OPTIONS/B747_8_FMC_Misc.js
* Restores support for flight planning using the default MSFS world map flight planner
* This option is disabled by default and we discourage the use of it unless you really don't want to use anything else
> Added optional support for world map flight planning

- salty-747/SimObjects/Airplanes/Asobo_B747_8i/panel/panel.xml
Added Seatbelts Memo.
As per FCOM:
SEATBELTS ON displays when switch manually selected on.
SEATBELTS OFF when switch selected off and not on the ground.
> Added Seatbelts Memo

- salty-747/html_ui/Pages/Salty/WT/Autopilot/SaltyNavModeSelector.js
- salty-747/html_ui/Pages/Salty/WT/Autopilot/WT_BaseVnav.js
- salty-747/html_ui/Pages/Salty/WT/Autopilot/WT_VnavAutopilot.js
- salty-747/html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/FMC/B747_8_FMC_LegsPage.js
- salty-747/html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/FMC/B747_8_FMC_MainDisplay.js
- salty-747/html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/FMC/B747_8_FMC_VNAVPage.js
Changed TOD calc logic, now should show in the proper location when arrival constraints are present.
Changed path to activate within a 350 foot window to give a smoother intercept, avoids getting high on path right at TOD. (was 150 previously)
Fixed auto-throttles sometimes holding constant N1 from TOD onward, causing overspeed in descent.
Fixed not being able to enter a constraint on the active leg on the legs page.
Fixed Mach/IAS cycling bug on descent.
> Some VNAV fixes

- salty-747/html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/PFD/AttitudeIndicator.js
Weirdly the default attitude indicator always had an error in displaying roll.
A correction factor has been applied to fix this.
> Fix Attitude indicator bank

- LICENSE
- Changes the license from MIT to GPLv3. This will disqualify Salty from the marketplace, however this decision was carefully thought over and decided by the team.
> MIT to GPLv3

- salty-747/SimObjects/Airplanes/Asobo_B747_8i/engines.cfg
Updated increased fuel flow to further match fuel consumption on long haul flights. Previous calculation has become inaccurate landing with in excess of 60,000+ lbs on long haul flights.
Short haul flights will have slightly more planned fuel burn, with long haul flights having slightly less planned fuel burn due to linear fuel burn from Asobo.
> Updated Fuel Flow

- salty-747/html_ui/Pages/Salty/WT/Autopilot/SaltyNavModeSelector.js
- salty-747/html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/FMC/Boeing_FMC.js
- FLCH now uses VNAV MCP SPD as initial target if selected while VNAV active and in speed intervention mode.
- FLCH now defaults to current IAS as initial target speed if no valid FMC speed available.
- Fixed bug requiring MCP speed knob to be pushed twice to open in some instances.
- Fixed bug causing VNAV CDU page to erroneously display MCP SPD mode in some instances.
> fix(AP): Fixes some AP bugs

- salty-747/SimObjects/Airplanes/Asobo_B747_8i/flight_model.cfg
Reduces the overdone ground effect during landing to an acceptable level.
Also fixes very sluggish control response when manually flying.
This has not been extensively tuned for accuracy and is intended only as a stopgap measure while the complete overhaul of the flight model is underway.
> feat(FM): Temporary fix for excessive ground effect and poor control response.

- salty-747/html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/EICAS/Pages/B747_8_LowerEICAS_Fuel.js
Fuel unit on upper EICAS uses settings from SatlyDataStore, but Lower EICAS uses the value from SimVar. Both EICAS now have the same unit displayed on startup.
> fix: lower EICAS fuel to match upper EICAS fuel unit

- salty-747/html_ui/Pages/Salty/WT/Autopilot/LNavDirector.js
- salty-747/html_ui/Pages/Salty/WT/Autopilot/NavToNavTransfer.js
- salty-747/html_ui/Pages/Salty/WT/Autopilot/SaltyNavModeSelector.js
- salty-747/html_ui/Pages/Salty/WT/Waypoint.js
- src/modules/src/fpm/flightplanning/FlightPlanManager.ts
- src/modules/src/fpm/flightplanning/RawDataMapper.ts
Updates some WT files to latest versions which fixes the issue of ILS failing to tune sometimes when selecting approach in CDU. 
Note it is still required to select the approach for now: the AP will not couple to a manually tuned ILS although the indications will now show correctly on PFD.
> fix(ILS): Fixes ILS failing to autotune in some instances.

- salty-747/SimObjects/Airplanes/Asobo_B747_8i/Climb.flt
- salty-747/SimObjects/Airplanes/Asobo_B747_8i/approach.FLT
- salty-747/SimObjects/Airplanes/Asobo_B747_8i/apron.FLT
- salty-747/SimObjects/Airplanes/Asobo_B747_8i/cruise.FLT
- salty-747/SimObjects/Airplanes/Asobo_B747_8i/final.FLT
- salty-747/SimObjects/Airplanes/Asobo_B747_8i/hangar.flt
- salty-747/SimObjects/Airplanes/Asobo_B747_8i/taxi.FLT
Added MaxBankIndex to other FLT files that were missing the index which was present in the runway.FLT file.
This PR is aimed to improve the LNAV tracking that is achieved by setting the Bank Angle Selector knob to AUTO when starting from a Cold and Dark flight.
Testing Instructions:
1. Start the sim fresh and spawn C&D.
2. Observe that the Bank Angle Selector knob is set to AUTO upon spawning.
> fix(model): Bank Angle Selector set to AUTO by default

- salty-747/html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/FMC/OPTIONS/B747_8_FMC_SaltyOptions.js
Adds an AP debug page on the lower EICAS accessible only through FMC > SALTY > DEBUG PAGE.
Shows current state of internal AP logic (and whatever else might be useful in future), users can submit screenshots to aid in troubleshooting the AP.
**Testing Instructions:
N/A**
> feat(Debug): AP Debug Page

- salty-747/html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/FMC/B747_8_FMC_PosInitPage.js
- salty-747/html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/FMC/FMCMainDisplay.js
- Fixes visual bug with groundspeed.
- Fixes a bug where pressing PREV PAGE on page 1/4 took you to page 3/4 instead of 4/4.
- Fixes a bug causing FMC not to change into CRZ or DES modes due to using wrong altimeter source.
**Testing instructions:**
Check FMC POS page 4 looks normal (GS displayed with no decimal places) when in flight. 
Check that cycling through the pages with NEXT PAGE and PREV page works as expected.
Using live weather, set a cruise altitude of FL360 in the FMC. Takeoff and check that CLB changes to CRZ on the upper EICAS mode when levelling off at FL360.
> fix(FMC): Fixed POS page 4 & Flightphase sequencing

- salty-747/html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/FMC/B747_8_FMC_PosReport.js
- salty-747/html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/FMC/Boeing_FMC.js
**Changes:**
VNAV will not be inhibited when there is no CRZ ALT entered in the PERF INIT page.
Fix ETA in Pos Report to not show UNDEFINED anymore. (Temporary fix until POS REPORT gets reworked)
**Testing instructions:**
Load up aircraft, do not enter a CRZ ALT, check if VNAV does not activate.
Check POS REPORT page, see if ETA shows UTC time instead of UNDEFINED.
> fix(fmc): Inhibit VNAV when there is no CRZ ALT + ETA in POS Report fix

- salty-747/html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/FMC/B747_8_FMC_LegsPage.js
- salty-747/html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/FMC/B747_8_FMC_VNAVPage.js
* fixes a bug where NaN would be displayed in the legs and vnav pages when no cruising altitude was set
> fix(fmc): nan in vnav and legs pages when no crz alt set

- salty-747/SimObjects/Airplanes/Salty_B747_8i/panel/panel.xml
- salty-747/html_ui/Pages/VCockpit/Instruments/Airliners/Salty_B747_8/PFD/AirspeedIndicator.js
Added AIRSPEED LOW caution message to EICAS.
Triggers when airspeed drops below min manuever band shown on PFD.
Effects: AIRSPEED LOW message shows on EICAS along with Caution tone. Airspeed indicator on PFD is highlighted in amber.
**Instructions for testing:**
**Accelerate and decelerate into the amber band speed and check warning triggers and blanks appropriately.**
**Confirm that above mentioned behaviours all occur.**
**Confirm that the message does not trigger when on the ground, during rotation or during the landing flare (It is at very low** **altitude to avoid nuisance warnings.)**
> Airspeed Low Caution

- salty-747/html_ui/Pages/Salty/SaltyConnection.js
- src/modules/src/fpm/cj4/fmc/CJ4_FMC_PilotWaypointParser.ts
Fixes #467 
* Fixed coordinates inserting at the wrong index
* The exit waypoint of an airway is now inserted as direct if airway is not found
* Added support for SimBrief's less common 11-character coordinate format ("6000N12830W")
**Instructions for testing**
* Test SimBrief uplink with the route `OMDB`-`KSEA`, make sure you get a route similar to this one with the long form coordinates: ![uplink](https://user-images.githubusercontent.com/26278705/189532560-7c8fe8c8-f3ee-4971-ba45-1f2c1823ad59.png). 
* Test other routes as well (note that depending on your airac cycle and other things, getting `PARTIAL ROUTE 1 UPLINK` may be normal).
> fix: simbrief uplink bugs

- salty-747/html_ui/Pages/VCockpit/Instruments/Airliners/Salty_B747_8/FMC/OPTIONS/B747_8_FMC_Misc.js
- src/modules/src/modules.ts
- src/modules/src/qol/AutoFuel.ts
* Adds an option in the CDU to enable automatic fuel management. This will automatically do all the interventions normally required to be done manually.
**Instructions for testing**
* Enable the option in salty options -> misc
* Do a full flight, make sure it is long enough so that you'd normally need to do all the steps in our fuel guide (alternatively you could test using the salty fueling menu as well)
* Make sure that:
* The stab pumps switch on when there is fuel inside the tanks and close when there is not
* The center pumps switch on when there is fuel inside the tanks and close when there is not
* When the outboard and inboard tanks are balanced (refer to our fuel guide), make sure that the OVRD/JETTISON pumps 2 & 3 switch off and crossfeed valves 1 & 4 close. You would normally …
> feat: automatic fuel management option

- salty-747/SimObjects/Airplanes/Salty_B747_8i-livery/MODEL.SALTY/747_8I.xml
- salty-747/SimObjects/Airplanes/Salty_B747_8i/model/747_8I.xml
Removed <MAX_VALUE>45</MAX_VALUE> from both model.xml's to allow the inboard spoilers to deploy properly. 
**INSTRUCTIONS TO TEST**
Load into base livery
Engage spoilers and verify both outboard and inboard spoilers deploy
Repeat above step with the Salty livery
> fix: re-enabled inboard spoilers

- src/instruments/src/EFB/components/TopBar.tsx
Adds clock & day on the topbar
> feat(efb): add dynamic time & day in topbar
